# Generated by Django 2.0.9 on 2024-12-10 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=400)),
                ('payment_date', models.CharField(max_length=400)),
                ('payment_mode', models.CharField(max_length=400)),
                ('amount', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='chat_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=600)),
                ('date', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='customers_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
                ('proof', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('latitude', models.CharField(max_length=400)),
                ('longitude', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='housedetail_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=400)),
                ('longitude', models.CharField(max_length=400)),
                ('rent', models.CharField(max_length=400)),
                ('image1', models.CharField(max_length=300)),
                ('image2', models.CharField(max_length=300)),
                ('image3', models.CharField(max_length=300)),
                ('information', models.CharField(max_length=400)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='houseowners_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('proof', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='login_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='rating_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customers_tb')),
                ('HOUSE_DETAILS', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.housedetail_tb')),
            ],
        ),
        migrations.AddField(
            model_name='houseowners_tb',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_tb'),
        ),
        migrations.AddField(
            model_name='housedetail_tb',
            name='OWNER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.houseowners_tb'),
        ),
        migrations.AddField(
            model_name='customers_tb',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_tb'),
        ),
        migrations.AddField(
            model_name='chat_tb',
            name='CUSTOMER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customers_tb'),
        ),
        migrations.AddField(
            model_name='chat_tb',
            name='OWNER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.houseowners_tb'),
        ),
        migrations.AddField(
            model_name='booking_tb',
            name='CUSTOMER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customers_tb'),
        ),
        migrations.AddField(
            model_name='booking_tb',
            name='ROOM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.housedetail_tb'),
        ),
    ]
